version: '3.4'
services:
  pg:
    # https://hub.docker.com/_/postgres/
    # Exposes port 5432 on container
    # We publishes the container port 5432 to the host port 5432
    image: postgres
    ports:
      # HOST:CONTAINER
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: passWORD!
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
